import sys,re,json; sys.path.insert(0,'/tmp/fb')
from harness import *
APP=sys.argv[1];O='organizations/org1/'
res=[]
def chk(n,c,e=''):
    res.append(bool(c));print('OK   ' if c else 'FALHA',n,e,flush=True)
IGN=lambda errs:[e for e in errs if "reading 'update'" not in e and 'xlsx.full.min.js' not in e and '404' not in e]
def seed():
    s=make_seed()
    for i in range(6): s[O+f'finance/fx{i}']=base(workId='w1',date=d(-10-i),dueDate=d(5+i),description=f'Lançamento de exemplo número {i} com descrição longa para testar quebra de linha no cartão',type='Despesa',category='Materiais',value=1000+i*250,status='Pendente')
    return s
def cls(pg): return pg.evaluate("[...document.documentElement.classList].filter(c=>c.startsWith('vm-'))")
def overflow(pg): return pg.evaluate("Math.max(document.documentElement.scrollWidth,document.body.scrollWidth)-Math.min(document.documentElement.clientWidth,screen.width)+Math.abs(innerWidth-document.documentElement.clientWidth)")
def box(pg,sel): return pg.evaluate("(s)=>{const e=document.querySelector(s);if(!e)return null;const r=e.getBoundingClientRect(),c=getComputedStyle(e);return{x:Math.round(r.left),y:Math.round(r.top),w:Math.round(r.width),h:Math.round(r.height),b:Math.round(r.bottom),r:Math.round(r.right),disp:c.display,vis:c.visibility,pos:c.position}}",sel)
# ================= CELULAR EM PÉ (390×844)
a=App(APP,auth=OWNER,seed=seed(),port=9400,viewport={'width':390,'height':844},mobile=True)
with a:
    a.open();pg=a.page;pg.wait_for_timeout(800)
    chk('M1 celular em pé entra sozinho na visualização de smartphone',cls(pg)==['vm-mobile'],str(cls(pg)))
    bn=box(pg,'#bottomNav');items=pg.eval_on_selector_all('.bnItem','e=>e.map(x=>x.querySelector("span").innerText.trim())')
    chk('M2 menu inferior fixo na base com Painel, Obras, Cronograma, Alertas e Mais',bn and bn['pos']=='fixed' and bn['b']>=840 and items==['Painel','Obras','Cronograma','Alertas','Mais'],f'{bn} {items}')
    chk('M3 o menu lateral fica escondido (gaveta) e a barra superior é compacta (52 px)',box(pg,'#sidebar')['vis']=='hidden' and box(pg,'.topbar')['h']<=56,str((box(pg,'#sidebar')['vis'],box(pg,'.topbar')['h'])))
    vb=box(pg,'#viewBtn');chk('M4 botão de alternância visível na barra superior, com ícone de computador (porque está em smartphone)',vb['w']>=40 and 'computador' in pg.get_attribute('#viewBtn','title') and pg.evaluate("document.querySelector('#viewBtn svg rect').getAttribute('width')")=='18',str(vb))
    chk('M5 indicador de sincronização vira uma bolinha e usuário/Sair saem da barra',box(pg,'#syncStatus')['w']<=12 and box(pg,'#logoutBtn')['disp']=='none')
    chk('M6 alvos de toque do menu inferior com pelo menos 48 px',all(h>=48 for h in pg.eval_on_selector_all('.bnItem','e=>e.map(x=>x.getBoundingClientRect().height)')))
    kp=pg.evaluate("getComputedStyle(document.querySelector('.kpis')).gridTemplateColumns.split(' ').length")
    chk('M7 indicadores em 2 colunas',kp==2,str(kp))
    bad=[]
    for rt in ('dashboard','works','finance','measurements','inventory','quality','contracts','settings','maintenance','alerts','budgets','suppliers','staff'):
        pg.evaluate(f"document.querySelector('.navbtn[data-route=\"{rt}\"]').click()");pg.wait_for_timeout(450)
        o=overflow(pg)
        if o>1: bad.append((rt,o))
    chk('M8 nenhuma das 13 telas conferidas rola para o lado (sem estouro de largura)',not bad,str(bad))
    # navegação
    pg.tap('.bnItem[data-route="works"]');pg.wait_for_timeout(500)
    chk('M9 tocar em Obras no menu inferior abre a tela e marca o item',pg.evaluate("document.querySelector('.bnItem.active').dataset.route")=='works' and 'Obras' in pg.inner_text('#content h1'))
    pg.tap('.bnItem[data-more]');pg.wait_for_timeout(400)
    sb=box(pg,'#sidebar');bk=box(pg,'#drawerBack')
    chk('M10 "Mais" abre a gaveta com o menu completo, rodapé (tema, visualização, sair) e fundo escurecido',sb['vis']=='visible' and sb['x']>=0 and sb['w']<=330 and pg.evaluate("document.querySelector('#drawerBack').classList.contains('show')") and pg.query_selector('#drvLogout') is not None,str(sb))
    pg.mouse.click(380,400);pg.wait_for_timeout(400)
    chk('M11 tocar fora da gaveta fecha',box(pg,'#sidebar')['vis']=='hidden')
    pg.tap('.bnItem[data-more]');pg.wait_for_timeout(300);pg.tap('.navbtn[data-route="contracts"]');pg.wait_for_timeout(500)
    chk('M12 escolher um item da gaveta navega e fecha a gaveta',box(pg,'#sidebar')['vis']=='hidden' and 'Contratos' in pg.inner_text('#content h1'))
    # filtros
    pg.tap('.bnItem[data-route="dashboard"]');pg.wait_for_timeout(400)
    f0=box(pg,'#globalFilters')['disp'];pg.tap('#filtersToggle');pg.wait_for_timeout(250);f1=box(pg,'#globalFilters')['disp']
    chk('M13 filtros começam recolhidos e abrem ao tocar no resumo',f0=='none' and f1=='grid' and 'Todas as obras' in pg.inner_text('#filtersToggle'),f'{f0}->{f1}')
    pg.select_option('#filterWork','w1');pg.wait_for_timeout(500)
    chk('M14 o resumo mostra a obra escolhida',  'Obra A' in pg.inner_text('#filtersToggle'),pg.inner_text('#filtersToggle'))
    pg.select_option('#filterWork','');pg.wait_for_timeout(200);pg.tap('#filtersToggle')
    # tabela vira cartões
    pg.tap('.bnItem[data-more]');pg.tap('.navbtn[data-route="finance"]');pg.wait_for_timeout(700)
    tb=pg.evaluate("(()=>{const t=document.querySelector('.tablewrap table'),tr=t&&t.querySelector('tbody tr'),td=tr&&tr.querySelector('td[data-label]');return{cards:t&&t.classList.contains('mcards'),thead:t&&getComputedStyle(t.tHead).display,label:td&&td.dataset.label,rows:t&&t.tBodies[0].rows.length,trw:tr&&Math.round(tr.getBoundingClientRect().width),rad:tr&&getComputedStyle(tr).borderRadius,labels:tr&&[...tr.querySelectorAll('td[data-label]')].map(x=>x.dataset.label).slice(0,5)}})()")
    chk('M15 a tabela do Financeiro vira lista de cartões com o nome de cada coluna',tb['cards'] and tb['thead']=='none' and tb['trw']<=380 and tb['rows']>=6 and 'Obra' in tb['labels'],str(tb))
    fab=box(pg,'#addRecord');bnb=box(pg,'#bottomNav')
    chk('M16 botão "Novo registro" vira botão flutuante acima do menu inferior',fab['pos']=='fixed' and fab['b']<=bnb['y'] and fab['h']>=48,f"{fab} menu em y={bnb['y']}")
    pg.screenshot(path='/tmp/fb/shots/m_financeiro_vertical.png')
    pg.tap('#addRecord');pg.wait_for_selector('#recordForm');pg.wait_for_timeout(300)
    dl=box(pg,'.dialog');inp=pg.evaluate("(()=>{const i=document.querySelector('#recordForm input:not([type=hidden]),#recordForm select');const c=getComputedStyle(i);return{fs:c.fontSize,h:Math.round(i.getBoundingClientRect().height)}})()")
    ac=box(pg,'.dialog .actions')
    chk('M17 formulário abre em tela cheia, com campos de 16 px/44 px e botões fixos na base',dl['w']>=388 and dl['h']>=840 and inp['fs']=='16px' and inp['h']>=44 and ac['b']>=835,f'{dl} {inp} {ac}')
    pg.screenshot(path='/tmp/fb/shots/m_formulario_vertical.png')
    pg.tap('#cancelModal');pg.wait_for_timeout(200)
    # cronograma
    pg.tap('.bnItem[data-route="activities"]');pg.wait_for_timeout(700)
    chk('M18 no cronograma, em pé, aparece a dica de virar o aparelho',pg.evaluate("getComputedStyle(document.querySelector('.ganttTop'),'::before').content").startswith('"Dica'))
    pg.tap('.bnItem[data-route="dashboard"]');pg.wait_for_timeout(500);pg.screenshot(path='/tmp/fb/shots/m_painel_vertical.png')
    chk('M19 sem erros de JavaScript (celular em pé)',not IGN(a.errors),str(IGN(a.errors)[:2]))
    # ---------- girar para horizontal
    pg.set_viewport_size({'width':844,'height':390});pg.wait_for_timeout(500)
    chk('H1 ao girar, entra no modo horizontal',cls(pg)==['vm-mobile','vm-landscape'],str(cls(pg)))
    bn=box(pg,'#bottomNav');tp=box(pg,'.topbar');ct=box(pg,'#content')
    chk('H2 o menu vira barra lateral esquerda (largura ~76 px) e a barra superior encolhe (≤46 px)',bn['x']==0 and 60<=bn['w']<=80 and bn['h']>=300 and tp['h']<=46,f'{bn} topo={tp["h"]}')
    pl=pg.evaluate("parseFloat(getComputedStyle(document.querySelector('#content')).paddingLeft)")
    chk('H3 o conteúdo começa depois da barra lateral (margem interna maior que a barra)',pl>=bn['r'],f"margem {pl} px, barra até {bn['r']}")
    kp=pg.evaluate("getComputedStyle(document.querySelector('.kpis')).gridTemplateColumns.split(' ').length")
    chk('H4 indicadores em 4 colunas na horizontal',kp==4,str(kp))
    chk('H5 sem estouro de largura na horizontal',overflow(pg)<=1,str(overflow(pg)))
    pg.screenshot(path='/tmp/fb/shots/m_painel_horizontal.png')
    pg.tap('.bnItem[data-route="activities"]');pg.wait_for_timeout(700)
    chk('H6 na horizontal a dica de girar some',pg.evaluate("getComputedStyle(document.querySelector('.ganttTop'),'::before').content")in('none','normal'))
    pg.screenshot(path='/tmp/fb/shots/m_cronograma_horizontal.png')
    pg.evaluate("document.querySelector('.navbtn[data-route=finance]').click()");pg.wait_for_timeout(600);fab=box(pg,'#addRecord')
    chk('H7 o botão flutuante fica no canto, sem cobrir a barra lateral',fab['x']>=300 and fab['b']<=390,str(fab))
    pg.tap('#addRecord');pg.wait_for_selector('#recordForm');pg.wait_for_timeout(300);dl=box(pg,'.dialog');cols=pg.evaluate("getComputedStyle(document.querySelector('.formgrid')).gridTemplateColumns.split(' ').length")
    chk('H8 formulário na horizontal ocupa a tela, em 2 colunas, rolando por dentro',dl['w']>=840 and cols==2,f'{dl} cols={cols}')
    pg.screenshot(path='/tmp/fb/shots/m_formulario_horizontal.png');pg.tap('#cancelModal')
    pg.set_viewport_size({'width':390,'height':844});pg.wait_for_timeout(500)
    chk('H9 voltar para em pé restaura o menu inferior',cls(pg)==['vm-mobile'] and box(pg,'#bottomNav')['b']>=840)
    # ---------- alternar para computador num celular
    pg.tap('#viewBtn');pg.wait_for_timeout(500)
    chk('T1 o botão troca para a visualização de computador e guarda a escolha',cls(pg)==['vm-desktop'] and pg.evaluate("localStorage.getItem('obratop-view')")=='desktop',str(cls(pg)))
    chk('T2 num celular, o modo computador usa a página larga (viewport 1280) e o botão passa a oferecer o smartphone',pg.evaluate("document.querySelector('meta[name=viewport]').content").startswith('width=1280') and pg.evaluate("document.querySelector('#viewBtn svg rect').getAttribute('width')")=='10' and 'smartphone' in pg.get_attribute('#viewBtn','title'),pg.evaluate("[document.querySelector('meta[name=viewport]').content,document.querySelector('#viewBtn svg rect').getAttribute('width'),document.querySelector('#viewBtn').title]"))
    pg.click('#viewBtn');pg.wait_for_timeout(500)
    chk('T3 e volta ao smartphone com outro toque (viewport normal)',cls(pg)==['vm-mobile'] and pg.evaluate("document.querySelector('meta[name=viewport]').content").startswith('width=device-width'))
    # ---------- tema escuro pela gaveta
    pg.tap('.bnItem[data-more]');pg.wait_for_timeout(300);pg.tap('#drvTheme');pg.wait_for_timeout(300)
    chk('T4 o tema escuro pode ser ligado pela gaveta',pg.evaluate("document.documentElement.dataset.theme")=='dark');pg.screenshot(path='/tmp/fb/shots/m_gaveta_escuro.png')
    pg.tap('#drawerBack') if False else pg.mouse.click(380,500)
    pg.evaluate("document.querySelector('#themeBtn').click()")
    chk('T5 sem erros de JavaScript (giro e alternância)',not IGN(a.errors),str(IGN(a.errors)[:2]))
# ================= COMPUTADOR: alternar para smartphone com moldura
b=App(APP,auth=OWNER,seed=seed(),port=9401,viewport={'width':1366,'height':768})
with b:
    b.open();pg=b.page;pg.wait_for_timeout(800)
    chk('D1 no computador, o modo automático mostra o layout completo (sem classes de smartphone)',cls(pg)==['vm-desktop'] and box(pg,'#bottomNav')['disp']=='none' and box(pg,'#viewBtn')['w']>0,str(cls(pg)))
    chk('D2 o botão oferece a visualização de smartphone (ícone de celular)','smartphone' in pg.get_attribute('#viewBtn','title') and pg.evaluate("document.querySelector('#viewBtn svg rect').getAttribute('width')")=='10')
    pg.click('#viewBtn');pg.wait_for_timeout(500)
    bd=box(pg,'body');bn=box(pg,'#bottomNav')
    chk('D3 ao alternar, a janela mostra o app dentro de uma moldura de celular centralizada (430 px)',cls(pg)==['vm-mobile','vm-frame'] and bd['w']==430 and abs(bd['x']-(1366-430)//2)<=2,f'{cls(pg)} {bd}')
    chk('D4 o menu inferior fica dentro da moldura',bn['x']==bd['x'] and bn['w']==430 and bn['b']>=766,str(bn))
    pg.evaluate("document.querySelector('.navbtn[data-route=finance]').click()");pg.wait_for_timeout(600);fab=box(pg,'#addRecord')
    chk('D5 o botão flutuante fica dentro da moldura',bd['x']<=fab['x'] and fab['r']<=bd['x']+430,f"{fab} moldura {bd['x']}-{bd['x']+430}")
    pg.click('#addRecord');pg.wait_for_selector('#recordForm');dl=box(pg,'.dialog');mb=box(pg,'.modalback')
    chk('D6 a janela de formulário também fica dentro da moldura',dl['w']==430 and abs(mb['x']-bd['x'])<=2 and mb['w']==430,f'{dl} {mb}')
    pg.screenshot(path='/tmp/fb/shots/m_moldura_formulario.png');pg.click('#cancelModal')
    pg.click('.bnItem[data-more]');pg.wait_for_timeout(400);sb=box(pg,'#sidebar')
    chk('D7 a gaveta abre dentro da moldura',sb['x']>=bd['x']-1 and sb['r']<=bd['x']+431 and sb['vis']=='visible',str(sb))
    pg.screenshot(path='/tmp/fb/shots/m_moldura_gaveta.png');pg.mouse.click(bd['x']+420,500);pg.wait_for_timeout(300)
    pg.reload();pg.wait_for_timeout(1500)
    chk('D8 a escolha continua depois de recarregar a página',cls(pg)==['vm-mobile','vm-frame'])
    pg.click('#viewBtn');pg.wait_for_timeout(500)
    chk('D9 outro clique volta ao computador',cls(pg)==['vm-desktop'] and box(pg,'#sidebar')['vis']=='visible')
    # Configurações
    pg.click('.navbtn[data-route="settings"]');pg.wait_for_timeout(500)
    chk('D10 Configurações traz as opções Automático, Computador e Smartphone','Automático' in pg.inner_text('.viewCard') and pg.eval_on_selector_all('input[name=viewPref]','e=>e.length')==3)
    pg.click('label.viewOpt:has(input[value=mobile])');pg.wait_for_timeout(500)
    chk('D11 escolher Smartphone nas Configurações muda a visualização',cls(pg)==['vm-mobile','vm-frame'])
    pg.click('.bnItem[data-more]');pg.click('.navbtn[data-route="settings"]');pg.wait_for_timeout(500);pg.click('label.viewOpt:has(input[value=auto])');pg.wait_for_timeout(500)
    chk('D12 e Automático devolve o layout de computador',cls(pg)==['vm-desktop'] and pg.evaluate("localStorage.getItem('obratop-view')")=='auto')
    chk('D13 sem erros de JavaScript (computador)',not IGN(b.errors),str(IGN(b.errors)[:2]))
print('\nRESUMO:',sum(res),'de',len(res));sys.exit(0 if all(res) else 1)
